# Generated by Django 4.1.3 on 2022-11-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('nom_classe', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('Name', models.CharField(max_length=70)),
                ('Matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=70)),
                ('place_birth', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('date_birth', models.DateField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('number', models.CharField(max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
            bases=('app.user',),
        ),
    ]
